language: python
python: 2.7
env:
  - TOXENV=py27-14
  - TOXENV=py27-15
  - TOXENV=py27-16
  - TOXENV=py27-17
  - TOXENV=py27-18
  - TOXENV=py27-19
  - TOXENV=py27-110
  - TOXENV=py33-15
  - TOXENV=py33-16
  - TOXENV=py33-17
  - TOXENV=py33-18
  - TOXENV=py34-15
  - TOXENV=py34-16
  - TOXENV=py34-17
  - TOXENV=py34-18
  - TOXENV=py34-19
  - TOXENV=py34-110
  - TOXENV=py35-18
  - TOXENV=py35-19
  - TOXENV=py35-110
  - TOXENV=pypy-14
  - TOXENV=pypy-15
  - TOXENV=pypy-16
  - TOXENV=pypy-17
  - TOXENV=pypy-18
  - TOXENV=pypy-19
  - TOXENV=pypy-110
  - TOXENV=docs
  - TOXENV=flake8
before_install:
  - sudo apt-get -q -y update

  # The following three lines is a fix for travis CI, since it wouldn't be
  # able to install the dependencies correctly.
  # See: https://github.com/travis-ci/travis-ci/issues/2683
  - sudo apt-get remove -q -y binutils gdal-bin libproj-dev libgeos-c1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

  # Required to install Pillow
  - sudo apt-get -q -y install build-essential
  # GIS requirements.
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1
install:
  # pip >= 8 dropped Python 3.2 support
  - pip install "pip<8.0.0" wheel
  - pip install tox
script:
  - tox
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: gremu
  password:
    secure: HAgxb7ebUfIQSfcxtjKoXO3FCBiujCo4GU2lYO8IUPeSdurPG6e+uABzwg88d7Zt1Zuay2eleAJzqhvwU2bCOKr68wjkNw3yWRslvLAMK3vj2LPPoWYsgmLJ1YiOvPloCdD2sIVSmpLEiN5HLUteh5j6D2BUbw67a9S2TXx1J8c=
  on:
    tags: true
    repo: gregmuellegger/django-floppyforms
    condition: "$TOXENV = py35-18"
